[package]
name = "risp8"
version = "0.1.0"
authors = ["Stovent <StoventTAS@gmail.com>"]
edition = "2021"
license = "MIT"
description = "A Chip8 interpreter, cached interpreter and JIT compiler in Rust, with both a library and an executable."
repository = "https://github.com/Stovent/risp8"
keywords = ["chip8", "emulator", "interpreter", "jit"]
categories = ["compilers", "emulators"]

[features]
default = ["tui", "gui"]
gui = ["dep:pixels", "dep:winit"]
tui = ["dep:crossterm", "dep:ratatui"]

[dependencies]
crossterm = { version = "0.27.0", optional = true }
kanal = "0.1.0-pre8"
pixels = { version = "0.13.0", optional = true }
rand = "0.7.0"
ratatui = { version = "0.26.1", optional = true }
winit = { version = "0.29.15", optional = true, default-features = false, features = ["rwh_05", "x11", "wayland", "wayland-dlopen", "wayland-csd-adwaita"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
dynasmrt = "2.0.0"
